theme: jekyll-theme-slate
title: Cancer Imaging, KCL
author: Cancer Imaging Department, King's College London
description: > 
  Cancer Imaging Department, School of Biomedical Engineering and Medical Sciences, 
  King's College London.  