# Site settings
title: KCL Cancer Imaging
description: > 
  Cancer Imaging Department, School of Biomedical Engineering and Medical Sciences, 
  King's College London.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author (Cancer Imaging Dept. details)
author:
  name   : "Cancer Imaging Department, King's College London"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "KCL Cancer Imaging Department's web pages"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.kcl.ac.uk/bmeis/our-departments/cancer-imaging"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CancerImagingKCL/cancerimagingkcl.github.io"

# Google site verification
google-site-verification:
  name  : "D1CVPpGV4h1wf5KWo1wtttFVRjvERSdO6TcictL1Y-w"

# Footer
footer:
  links:
    - label: "King's website"
      icon: "fas fa-fw fa-link"
      url: "https://www.kcl.ac.uk/bmeis/our-departments/cancer-imaging"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CancerImagingKCL/cancerimagingkcl.github.io"

# Default page values
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
